module.exports = notifications = [
  {
    id: "dgw65",
    userId: "wegwgew",
    user: "#SDGF-DGDS",
    avatar: "/images/temporary/Avatar4.png",
    content: "Some one has disagreed with your post 'The Epistle of Paul'",
    icon: "/images/post.svg",
    color: "#ec3b3b",
    type: "diagreee",
  },
  {
    id: "dg453w",
    userId: "wegwgew",
    user: "#SDGF-DGDS",
    avatar: "/images/temporary/Avatar4.png",
    content: "Some one has agreed with your post 'The Epistle of Paul'",
    icon: "/images/post.svg",
    color: "#80e452",
    type: "agree",
  },
  {
    id: "dg2343w",
    userId: "wegwgew",
    user: "#SDGF-DGDS",
    avatar: "/images/temporary/Avatar4.png",
    content: "Some one has commented on your post 'The Epistle of Paul'",
    icon: "/images/post.svg",
    color: "#43a9f7",
    type: "comment",
  },
  {
    id: "dgw",
    userId: "wegwgew",
    user: "#SDGF-DGDS",
    avatar: "/images/temporary/Avatar4.png",
    content: "Try the new featured available",
    icon: "/images/post.svg",
    color: "#dae5ed",
    type: "system",
  },
  {
    id: "dgw6509657560",
    userId: "wegwgew",
    user: "#SDGF-DGDS",
    avatar: "/images/temporary/Avatar4.png",
    content: "Some one has disagreed with your post 'The Epistle of Paul'",
    icon: "/images/post.svg",
    color: "#ec3b3b",
    type: "diagreee",
  },
  {
    id: "dg45323w",
    userId: "wegwgew",
    user: "#SDGF-DGDS",
    avatar: "/images/temporary/Avatar4.png",
    content: "Some one has agreed with your post 'The Epistle of Paul'",
    icon: "/images/post.svg",
    color: "#80e452",
    type: "agree",
  },
  {
    id: "dg2343765w",
    userId: "wegwgew",
    user: "#SDGF-DGDS",
    avatar: "/images/temporary/Avatar4.png",
    content: "Some one has commented on your post 'The Epistle of Paul'",
    icon: "/images/post.svg",
    color: "#43a9f7",
    type: "comment",
  },
  {
    id: "d65765gw",
    userId: "wegwgew",
    user: "#SDGF-DGDS",
    avatar: "/images/temporary/Avatar4.png",
    content: "Try the new featured available",
    icon: "/images/post.svg",
    color: "#dae5ed",
    type: "system",
  },
];
