module.exports = sermonsbyJVM = [
  {
    tagColors: [],
    _id: "613b83a0b01f85108898eeb6",
    thumbnail: "/images/library/twas-the-prayer-before-christmass.png",
    title: "'Twas the Prayer Before Christmas",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "'Twas the Prayer Before Christmas by J Vernon McGee",
    categoryTags: ["#PPL", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=IgglIs2AmrA",
  },
  {
    tagColors: [],
    _id: "613d26727258c555c088648f",
    thumbnail: "/images/library/a-law-concerning-cleansing.png",
    title: "A Law Concerning Cleansing",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Christ’s first coming wasn’t for judgment, but to provide a way of peace, reconciling men to God. But His second coming will be for the judgment of all who have forsaken the free offering of salvation that He came to provide the first time.",
    categoryTags: ["#BL", "#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=uHhi68dkB9M",
  },
  {
    tagColors: [],
    _id: "6140cccbbaf4b8a1ed78a94f",
    thumbnail: "/images/library/a-trip-to-the-zoo.png",
    title: "A Trip to the Zoo",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "A Trip to the Zoo by  J Vernon McGee",
    categoryTags: ["#PPL", "#LB"],
    sermonUrl: "https://www.youtube.com/watch?v=jR05OXi2cAw",
  },
  {
    tagColors: [],
    _id: "6140d468baf4b8a1ed78a966",
    thumbnail: "/images/library/abounding-grace.png",
    title: "Abounding Grace",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "(2 Corinthians 8, 9) Does God require a tithe? Are we commanded to give 10% of our salaries? Paul makes the issue of giving abundantly clear in his second letter to the Corinthians.",
    categoryTags: ["#DR"],
    sermonUrl: "https://www.youtube.com/watch?v=rUAei-BWylA",
  },
  {
    tagColors: [],
    _id: "613d281584c52bafdaaac4f9",
    thumbnail: "/images/library/amazing-alarming-and-awful-apostasy.png",
    title: "Amazing, Alarming, and Awful Apostasy",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "The apostasy is coming—blatant immorality, rejection of God’s Word, and denial of Christ as our Lord. In this message Dr. McGee details the apostasy in the twentieth century.",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=MBY5Nv8CPGY",
  },
  {
    tagColors: [],
    _id: "613a6315a749fb4edf1205b6",
    thumbnail: "/images/library/an-x-ray-at-the-cross.png",
    title: "An X-Ray at the Cross",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "An X-Ray at the Cross by J Vernon McGee",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=bymZECEdbVw",
  },
  {
    tagColors: [],
    _id: "6140c2ccbaf4b8a1ed78a930",
    thumbnail: "/images/library/angels-with-dirty-faces.png",
    title: "Angels with Dirty Faces",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Angels with Dirty Faces by J Vernon McGee",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=bI7GyoOhiPU",
  },
  {
    tagColors: [],
    _id: "6140d0e4baf4b8a1ed78a95c",
    thumbnail: "/images/library/another-look-at-the-lord.png",
    title: "Another Look at the Lord",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Dr. J. Vernon McGee argues that the great tragedy today is that Christians are not meditating on the Word of God and the person of the Lord Jesus Christ.",
    categoryTags: ["#RD", "#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=1ML9Fim72zA",
  },
  {
    tagColors: [],
    _id: "6140d14dbaf4b8a1ed78a95d",
    thumbnail: "/images/library/behold-a-reaper-went-forth-to-reap.png",
    title: "Behold, A Reaper Went Forth to Reap",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "(Galatians 6:7-9) It may seem obvious that whatever you sow is what you're going to reap, but it's that very principle that Paul had to teach to the churches of Galatia",
    categoryTags: ["#GR", "#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=xVYmsDOiY5I",
  },
  {
    tagColors: [],
    _id: "613d23527258c555c0886486",
    thumbnail:
      "/images/library/bright-and-morning-star-and-son-of-righteusness.png",
    title: "Bright and Morning Star and the Son of Righteousness",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Dr. McGee turns our attention to the heavens which, as the Psalmist says, “declare the glory of God” and reveal to us the bright and morning star of Scripture and the Son of Righteousness.",
    categoryTags: ["#BL", "#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=6CIFcHHRtg4",
  },
  {
    tagColors: [],
    _id: "613d3a8984c52bafdaaac52e",
    thumbnail: "/images/library/charge-it.png",
    title: "Charge it!",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Credit itself is not good or bad; it’s a tool you can control for good or which can control you when the debt becomes too overwhelming. Paul uses another kind of credit when dealing with reconciliation between a slave and his master.",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=kbnYMK-B3uE",
  },
  {
    tagColors: [],
    _id: "6140cc94baf4b8a1ed78a94e",
    thumbnail: "/images/library/confidence-certainty-cheer.png",
    title: "Confidence, Certainty, Cheer",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Confidence, Certainty, Cheer by  J Vernon McGee",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=bzpCjfQ8_uU",
  },
  {
    tagColors: [],
    _id: "613d398884c52bafdaaac52b",
    thumbnail: "/images/library/daniel-a-man-of-preayers.png",
    title: "Daniel: A Man of Prayer",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "The neglect of prayer has affected all areas of the Christian's personal life and the total life of the church. That is why we need to see men like Daniel as our models for prayer.",
    categoryTags: ["#OR", "#GN"],
    sermonUrl: "https://www.youtube.com/watch?v=zqKGbpX4ekE",
  },
  {
    tagColors: [],
    _id: "613d3a2584c52bafdaaac52d",
    thumbnail: "/images/library/daniel-choosing-to-stand-alone.png",
    title: "Daniel: Choosing to Stand Alone",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Throughout history, we have venerated and highly esteemed those who—in the midst of temptation, turmoil, trials and troubles—have stayed the course and followed God, unmoved by the opposition they faced. Daniel is one such man.",
    categoryTags: ["#OR", "#GN"],
    sermonUrl: "https://www.youtube.com/watch?v=6ZocLznKCBo",
  },
  {
    tagColors: [],
    _id: "613d28a284c52bafdaaac4fb",
    thumbnail: "/images/library/darkness-and-light-the-day-of-the-lord.png",
    title: "Darkness and Light: The Day of the Lord",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "If you’ve ever been confused about prophecy, this is the booklet for you. Dr. McGee clearly spells out God’s scenario for the future as described in the Bible, event by event, from the Rapture to the New Jerusalem.",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=B01x87t9SvU",
  },
  {
    tagColors: [],
    _id: "6140c24cbaf4b8a1ed78a92f",
    thumbnail: "/images/library/dead-bones-in-death-valley.png",
    title: "Dead Bones in Death Valley",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Dead Bones in Death Valley by J Vernon McGee",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=OMpLZfOikLk",
  },
  {
    tagColors: [],
    _id: "613d377084c52bafdaaac524",
    thumbnail: "/images/library/delivered-from-death.png",
    title: "Delivered From Death",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "How one perceives the issue of death speaks volumes about who they are. But no matter what, one thing is true: It’s the end of life on this earth. But is death really the final stage of this life, with no hope for a future beyond?",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=uNMflpPW9vQ",
  },
  {
    tagColors: [],
    _id: "6140cfd3baf4b8a1ed78a959",
    thumbnail: "/images/library/delivered-out-of-death-the-foundation.png",
    title: "Delivered Out of Death",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Delivered Out of Death by  J Vernon McGee",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=TpTE5mcak3k",
  },
  {
    tagColors: [],
    _id: "613d2ca384c52bafdaaac507",
    thumbnail: "/images/library/demas-diotrephes-and-demetrius.png",
    title:
      "Demas, Diotrephes, and Demetrius: You Will Find Them in the Yellow Pages",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Paul mentions many of his fellow workers, such as Julia, Rufus, and Junias. He names some in almost all of his letters, and John and Peter do the same. So who are these saints? How did they live for Christ, or did they?  ",
    categoryTags: ["#OR", "#PNK"],
    sermonUrl: "https://www.youtube.com/watch?v=j9oMmBM0zIU",
  },
  {
    tagColors: [],
    _id: "6140c7fbbaf4b8a1ed78a93f",
    thumbnail: "/images/library/divine-election-and-human-free-will.png",
    title: "Divine Election and Human Free Will",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Divine Election and Human Free Will J Vernon McGee",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=bf2fLdRE_EI",
  },
  {
    tagColors: [],
    _id: "613d29db84c52bafdaaac4ff",
    thumbnail: "/images/library/does-god-ever-change-his-mind.png",
    title: "Does God Ever Change His Mind?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Living in an age of technological and scientific discovery, we may ask whether or not God changes to accommodate our transitioning world. But God is perfect, and by definition there’s no need for perfection to change.",
    categoryTags: ["#CYN"],
    sermonUrl: "https://www.youtube.com/watch?v=skZpTl7S2EA",
  },
  {
    tagColors: [],
    _id: "6140cd7bbaf4b8a1ed78a951",
    thumbnail: "/images/library/does-god-hate.png",
    title: "Does God Hate?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Does God Hate? by  J Vernon McGee",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=K7TDxO0vCf4",
  },
  {
    tagColors: [],
    _id: "61391028e23d117056d1f306",
    thumbnail: "/images/library/watch/endorsing-a-bad-note.png",
    title: "Endorsing A Bad Note",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Endorsing A Bad Note by J Vernon McGee",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=U9u4huqwBdo",
  },
  {
    tagColors: [],
    _id: "6140d201baf4b8a1ed78a95f",
    thumbnail: "/images/library/faith-plus-nothing-equals-salvation.png",
    title: "Faith Plus Nothing Equals Salvation",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "(Galatians 4) What are the requirements for salvation? In Paul’s letter to the Galatians he deals with the nature of Law and grace and how they relate to the salvation offered to us through Jesus Christ.",
    categoryTags: ["#GR", "#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=fDR0mu18x80",
  },
  {
    tagColors: [],
    _id: "6140cf8cbaf4b8a1ed78a958",
    thumbnail: "/images/library/faith-and-freedom-and-the-foundation.png",
    title: "Faith and Freedom and the Foundation",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Faith and Freedom and the Foundation by  J Vernon McGee",
    categoryTags: ["#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=z71x3Rt1rdQ",
  },
  {
    tagColors: [],
    _id: "6140d3a0baf4b8a1ed78a963",
    thumbnail: "/images/library/for-such-a-time-as-this.png",
    title: "For Such a Time as This",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "(Job 1, 2) On any given day of the week the media reports on stories of violence, war, natural disasters, and the devastation to human life caused by famine and illness. So why does suffering occur in the lives of God’s children?",
    categoryTags: ["#PNK", "#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=VL0u7KX53jw",
  },
  {
    tagColors: [],
    _id: "6140d1aebaf4b8a1ed78a95e",
    thumbnail: "/images/library/fruit-more-fruit-and-much-fruit.png",
    title: "Fruit, More Fruit, Much Fruit",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "(Galatians 5:22, 23) Jesus made it clear that the evidence that someone is a Christian is the fruit they bear. But what evidence of fruit bearing should we find in our own lives as we examine whether or not we’re in the faith?",
    categoryTags: ["#GR", "#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=XHhotA7iuUo",
  },
  {
    tagColors: [],
    _id: "613b8292b01f85108898eeb5",
    thumbnail: "/images/library/glad-tithings-of-great-joy.png",
    title: "Glad Tidings of Great Joy",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Glad Tidings of Great Joy by J Vernon McGee",
    categoryTags: ["#RD", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=UJWoU7MgaUA",
  },
  {
    tagColors: [],
    _id: "613d2e3f84c52bafdaaac50b",
    thumbnail: "/images/library/god-of-the-second-chance.png",
    title: "God of the Second Chance",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "When you break God’s law, you’ve committed sin; the consequence, ultimately, is death. But grace and mercy turn us from the wrath of  judgment to the loving arms of the Father.",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=qslSEc34YsI",
  },
  {
    tagColors: [],
    _id: "6140c422baf4b8a1ed78a933",
    thumbnail: "/images/library/gods-answer-to-problems-in-times-like-this.png",
    title: "God's Answer to Problems in Times Like These",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "God's Answer to Problems in Times Like These by J Vernon McGee",
    categoryTags: ["#OR", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=f1eX1tbsmCw",
  },
  {
    tagColors: [],
    _id: "613d39ce84c52bafdaaac52c",
    thumbnail: "/images/library/gods-calendar-for-israel.png",
    title: "God's Calendar for Israel",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "With every wind of change in the news there are those who attempt to use events to determine the exact date that the Lord will return for the church. Although the day and hour of Christ’s return is unknowable, there is a very precise prophetic calendar in Scripture.",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=XCDejS3v2ns",
  },
  {
    tagColors: [],
    _id: "613d323f84c52bafdaaac514",
    thumbnail: "/images/library/gods-war-on-poverty-and-riches.png",
    title: "God’s War on Poverty and Riches",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "It’s been said that the rich are getting richer and the poor are getting poorer. Whether this statement is true or not, God has a plan to deal with both riches and poverty.",
    categoryTags: ["#CYN", "#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=YCD13fCkESI",
  },
  {
    tagColors: [],
    _id: "613d328c84c52bafdaaac515",
    thumbnail: "/images/library/gods-war-on-poverty-and-riches.png",
    title: "God’s War on Poverty and Riches",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "It’s been said that the rich are getting richer and the poor are getting poorer. Whether this statement is true or not, God has a plan to deal with both riches and poverty.",
    categoryTags: ["#CYN", "#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=YCD13fCkESI",
  },
  {
    tagColors: [],
    _id: "613d2dcc84c52bafdaaac50a",
    thumbnail: "/images/library/going-the-wrong-way-in-a-one-way-street.png",
    title: "Going the Wrong Way on a One-Way Street",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Turning your back on God is like going the wrong way on a one-way street. The life of the prophet Jonah illustrates how God deals with His children who turn from Him.",
    categoryTags: ["#GN", "YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=_xYILMP677g",
  },
  {
    tagColors: [],
    _id: "613d17b77258c555c0886473",
    thumbnail: "/images/library/golden-bells-and-pomegranets.png",
    title: "Golden Bells and Pomegranates",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "The high priest’s robe of the ephod had around the hem golden bells interspersed with pomegranates. Dr. McGee likens the bells to a believer’s verbal convictions and pomegranates to the fruit of a believer’s life.",
    categoryTags: ["#PPL", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=epn98U0qUvo",
  },
  {
    tagColors: [],
    _id: "613d15f6e3dd4223ebd7e1c9",
    thumbnail: "/images/library/grace-in-three-time-zones.png",
    title: "Grace in Three Time Zones",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=nwNVT1t5Qi4",
  },
  {
    tagColors: [],
    _id: "613d20297258c555c088647d",
    thumbnail: "/images/library/he-is-coming-again.png",
    title: "He is Coming Again!",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Paul says that we are looking for that blessed hope—that is, the day when Christ will come again. What will that be like, and when will it happen?",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=kiesX1b0YKE",
  },
  {
    tagColors: [],
    _id: "613d1ef67258c555c088647a",
    thumbnail: "/images/library/hell-fact-or-fiction.png",
    title: "Hell: Fact or Fiction?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Satan’s lie throughout the ages has been, “Ye shall not surely die.” However, the Word of God makes it clear that those who don’t come to Jesus as Savior are lost forever",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=SWMONSGl1eg",
  },
  {
    tagColors: [],
    _id: "613d2a5c84c52bafdaaac501",
    thumbnail: "/images/library/how-bi-is-god.png",
    title: "How Big is God?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "To answer this question we would need an entirely new measuring stick, because God cannot be compared to anything on earth. He is infinite in stature and influence.",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=dqcUkhoc2Bw",
  },
  {
    tagColors: [],
    _id: "613d2d2184c52bafdaaac508",
    thumbnail: "/images/library/how-to-have-fellowship-with-god.png",
    title: "How to Have Fellowship With God",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Christians are to be in fellowship with God, but we find it difficult to do so with a God we cannot see. Dr. McGee provides spiritual insight as he helps us to understand the process of fellowshipping with God.",
    categoryTags: ["#GN"],
    sermonUrl: "https://www.youtube.com/watch?v=hP2wm4c3mKw",
  },
  {
    tagColors: [],
    _id: "6140caf3baf4b8a1ed78a94a",
    thumbnail: "/images/library/in-the-days-of-thy-youth.png",
    title: "In the Days of Youth",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "In the Days of Youth by  J Vernon McGee",
    categoryTags: ["#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=htoDpbtihSo",
  },
  {
    tagColors: [],
    _id: "613d37da84c52bafdaaac525",
    thumbnail:
      "/images/library/is-it-possible-for-a-saved-person-to-be-lost.png",
    title: "Is it Possible For a Saved Person Ever to be Lost?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "In an honest search for its meaning, Dr. McGee tackles this confusing and difficult passage of Scripture, which is oftentimes skipped over by Bible commentators.",
    categoryTags: ["#GN"],
    sermonUrl: "https://www.youtube.com/watch?v=pkYiIs5P1-M",
  },
  {
    tagColors: [],
    _id: "613d382e84c52bafdaaac526",
    thumbnail:
      "/images/library/is-it-possible-for-a-saved-person-to-be-lost.png",
    title: "Is it Possible For a Saved Person Ever to be Lost?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "In an honest search for its meaning, Dr. McGee tackles this confusing and difficult passage of Scripture, which is oftentimes skipped over by Bible commentators.",
    categoryTags: ["#GN"],
    sermonUrl: "https://www.youtube.com/watch?v=pkYiIs5P1-M",
  },
  {
    tagColors: [],
    _id: "613d22917258c555c0886484",
    thumbnail:
      "/images/library/is-the-curtain-of-prophesy-ready-to-go-up-in-the-middle-east.png",
    title: "Is the Curtain of Prophecy Ready to Go Up in the Near East?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Trouble seems to be constantly brewing among the nations of the Middle East. There are wars, bombings, and complete unrest. Is this a fulfillment of prophecy or only “birth pains”?",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=TS_-9eS_4ww",
  },
  {
    tagColors: [],
    _id: "6140c7c0baf4b8a1ed78a93e",
    thumbnail: "/images/library/israel-the-bible-bomb.png",
    title: "Israel: The Bible Bomb",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Israel: The Bible Bomb J Vernon McGee",
    categoryTags: ["#OR", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=rFwrfkthRKM",
  },
  {
    tagColors: [],
    _id: "6140c648baf4b8a1ed78a939",
    thumbnail: "/images/library/jeremiah-gods-crybaby.png",
    title: "Jeremiah: God's Crybaby",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Jeremiah: God's Crybaby by J Vernon McGee",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=uDFgKASHq68",
  },
  {
    tagColors: [],
    _id: "6140c58dbaf4b8a1ed78a937",
    thumbnail:
      "/images/library/jeremiah-the-man-of-sorrows-of-the-old-testament.png",
    title: "Jeremiah: The Man of Sorrows of the Old Testament",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Jeremiah: The Man of Sorrows of the Old Testament by J Vernon McGee",
    categoryTags: ["#OR", "#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=nCN1vcZjKXo",
  },
  {
    tagColors: [],
    _id: "6140c983baf4b8a1ed78a945",
    thumbnail: "/images/library/jesus-came-through-the-line-of-david.png",
    title: "Jesus Came Through the Line of David",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Jesus Came Through the Line of David J Vernon McGee",
    categoryTags: ["#OR", "#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=tIHm2dvd0rE",
  },
  {
    tagColors: [],
    _id: "613a6db3a34e981dde7c4eab",
    thumbnail: "/images/library/john-written-for-the-wretched-man.png",
    title: "John, Written for the Wretched Man",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "John, Written for the Wretched Mans by J Vernon McGee",
    categoryTags: ["#PPL", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=9HEj1ZRUSo0",
  },
  {
    tagColors: [],
    _id: "613d32d384c52bafdaaac517",
    thumbnail: "/images/library/justification-by-works.png",
    title: "Justification By Works",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "When James discussed works, he was referring to the works that faith produces—the actions that follow faith in Christ. On this point, he and Paul are in perfect agreement.",
    categoryTags: ["#GN", "#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=K7pXmNznrZw",
  },
  {
    tagColors: [],
    _id: "613a6714a749fb4edf1205b7",
    thumbnail: "/images/library/king-salomon-and-the-queen-of-sheba.png",
    title: "King Salomon And The Queen of Sheba",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "King Salomon And The Queen of Sheba by J Vernon McGee",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=ibuqMmmweL0",
  },
  {
    tagColors: [],
    _id: "613b8bf5b01f85108898eeb8",
    thumbnail: "/images/library/listen-to-a-picture.png",
    title: "Listen to a Picture",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Listen to a Picture by J Vernon McGee",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=oloTuFh-dNY",
  },
  {
    tagColors: [],
    _id: "613d36e684c52bafdaaac522",
    thumbnail: "/images/library/looking-at-faith-in-the-laboratory-of-life.png",
    title: "Looking at Faith in the Laboratory of Life",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Faith is the substance of things hoped for, the evidence of things not seen.” But does that really help us understand what faith is or how it works? Fortunately, the writer of Hebrews goes on to illustrate faith in the lives of men and women God has used in times past.",
    categoryTags: ["#GN"],
    sermonUrl: "https://www.youtube.com/watch?v=wXx1VNVDdXo",
  },
  {
    tagColors: [],
    _id: "613a6f34a34e981dde7c4eac",
    thumbnail: "/images/library/luke—written-for-the-thinking-man.png",
    title: "Luke Written for the Thinking Man",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Luke, Written for the Thinking Man by J Vernon McGee",
    categoryTags: ["#CYN"],
    sermonUrl: "https://www.youtube.com/watch?v=uRJrI6Y_YgY",
  },
  {
    tagColors: [],
    _id: "613d2d7684c52bafdaaac509",
    thumbnail: "/images/library/major-motivation-for-missions.png",
    title: "Major Motivation for Missions",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "What would motivate you to take the gospel to people whom you hated with all your heart? Surprisingly, the answer to that question is found in the Book of Jonah and in God’s heart.",
    categoryTags: ["#GN", "YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=OIbKttEZh5E",
  },
  {
    tagColors: [],
    _id: "6140cb39baf4b8a1ed78a94b",
    thumbnail: "/images/library/man-versus-machine.png",
    title: "Man Versus Machine",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Man Versus Machine by  J Vernon McGee",
    categoryTags: ["#CYN"],
    sermonUrl: "https://www.youtube.com/watch?v=-2HP3uESdts",
  },
  {
    tagColors: [],
    _id: "613d28f084c52bafdaaac4fc",
    thumbnail: "/images/library/mans-question-gods-answer.png",
    title: "Man's Question, God's Answer",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Habakkuk was saying to God, “My country is in a mess! Why don’t You do something about it?” If you are asking “Why, God?” about anything, you can identify with Habakkuk and profit from God’s answer to him.",
    categoryTags: ["#CYN"],
    sermonUrl: "https://www.youtube.com/watch?v=_a0sgwTWTrQ",
  },
  {
    tagColors: [],
    _id: "613b7fadb01f85108898eeb3",
    thumbnail: "/images/library/mark-written-for-the-strong-man.png",
    title: "Mark, Written for the Strong Man",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Mark, Written for the Strong Man by J Vernon McGee",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=preeHZm5b2c",
  },
  {
    tagColors: [],
    _id: "613b8045b01f85108898eeb4",
    thumbnail: "/images/library/matthew-written-for-the-religious-man.png",
    title: "Matthew, Written for the Religious Man",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Matthew, Written for the Religious Man by J Vernon McGee",
    categoryTags: ["#GR", "#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=Qf808e6P9KE",
  },
  {
    tagColors: [],
    _id: "6140c686baf4b8a1ed78a93a",
    thumbnail: "/images/library/mystery-of-iniquity.png",
    title: "Mystery of Iniquity",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Mystery of Iniquity by J Vernon McGee",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=PpZ9vKb3nEE",
  },
  {
    tagColors: [],
    _id: "613d1b837258c555c0886475",
    thumbnail: "/images/library/on-eagles-wings.png",
    title: "On Eagles’ Wings",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Dr. McGee tells the story of how God brought Israel from slavery in Egypt to security in the land of promise on the eagle’s wings of His grace. In the same way, God also delivers us from sin.",
    categoryTags: ["#BR", "#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=CLqqDwqPDlg",
  },
  {
    tagColors: [],
    _id: "613d304184c52bafdaaac50f",
    thumbnail:
      "/images/library/one-of-the-many-infallible-proofs-of-the-resurrection.png",
    title: "One of the Many Infallible Proofs of the Resurrection",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "The Resurrection is the cornerstone of the Christian faith: Without it, Christianity as we know it wouldn’t exist. So it’s important to know that the events surrounding it are right and true. This Easter sermon will provide you with a greater understanding of the reality of the Resurrection.",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=iNDcRKtJLQo",
  },
  {
    tagColors: [],
    _id: "6140cb7abaf4b8a1ed78a94c",
    thumbnail: "/images/library/over-the-moon-under-the-sun.png",
    title: "Over the Moon but Under the Sun",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Over the Moon but Under the Sun by  J Vernon McGee",
    categoryTags: ["#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=o2rJeGDPqgE",
  },
  {
    tagColors: [],
    _id: "613913a0e23d117056d1f308",
    thumbnail: "/images/library/power-in-the-present-hour.png",
    title: "Power in the Present Hour",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Power in the Present Hour by J Vernon McGee",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=I4Nc1eQR0rk",
  },
  {
    tagColors: [],
    _id: "613d319784c52bafdaaac512",
    thumbnail: "/images/library/prayer-and-faith-healing.png",
    title: "Prayer and Faith Healing",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      'When Isaiah said, "By His stripes we are healed," did he mean that those who have faith to believe God today can expect healing for their bodies? And does the Bible tell us what Christians ought to do when they get sick?',
    categoryTags: ["#GN", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=h_6L6flqC4s",
  },
  {
    tagColors: [],
    _id: "6140c4d5baf4b8a1ed78a935",
    thumbnail: "/images/library/remember-jesus-christ.png",
    title: "Remember Jesus Christ",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Remember Jesus Christ",
    categoryTags: ["#PPL", "#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=CqIMPJaxeWE",
  },
  {
    tagColors: [],
    _id: "6140d62dbaf4b8a1ed78a96b",
    thumbnail: "/images/library/revival-and-survival.png",
    title: "Revival and Survival",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "revival and survival by J Vernon McGee",
    categoryTags: ["#BL", "#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=N0ln6xYWrCY",
  },
  {
    tagColors: [],
    _id: "6140cf38baf4b8a1ed78a957",
    thumbnail: "/images/library/singing-the-lords-song-in-a-strange-land.png",
    title: "Singing the Lord's Song in a Strange Land",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Singing the Lord's Song in a Strange Land by  J Vernon McGee",
    categoryTags: ["#BR", "#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=HdlH2YKxvNs",
  },
  {
    tagColors: [],
    _id: "613d2ae284c52bafdaaac503",
    thumbnail: "/images/library/something-god-has-not-seen.png",
    title: "Something God Has Not Seen",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "If you compiled a list of all the things you’d like to see but haven’t, it would be quite long. Consider the Great Wall of China, the Eiffel Tower, or even the end of war or a cure for cancer. But you might be surprised to know that there’s one thing that God hasn’t seen.",
    categoryTags: ["#GN"],
    sermonUrl: "https://www.youtube.com/watch?v=XPaGvpi3CLc",
  },
  {
    tagColors: [],
    _id: "6140d4cebaf4b8a1ed78a967",
    thumbnail: "/images/library/something-new-under-the-sun.png",
    title: "Something New Under the Sun",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "",
    categoryTags: ["#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=DkxXwVnQoPs",
  },
  {
    tagColors: [],
    _id: "613d30c084c52bafdaaac510",
    thumbnail: "/images/library/sparks-fly-upward.png",
    title: "Sparks Fly Upward",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "According to the Book of Job, man is born into suffering just as sparks fly upward. First Peter provides us with the godly principles to help us deal with our suffering.",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=HvHKwrLLxmM",
  },
  {
    tagColors: [],
    _id: "613d316b84c52bafdaaac511",
    thumbnail: "/images/library/strange-sufferings-of-the-saints.png",
    title: "Strange Sufferings of the Saints",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Suffering is universal—no matter the life, race, religion, gender, or economic status, everyone at some point will suffer. But why should God’s saints endure suffering?",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=FYUD-LXA8NA",
  },
  {
    tagColors: [],
    _id: "6140d019baf4b8a1ed78a95a",
    thumbnail: "/images/library/success-at-the-summit.png",
    title: "Success at the Summit",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Success at the Summit by  J Vernon McGee",
    categoryTags: ["#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=90BM9V7fV40",
  },
  {
    tagColors: [],
    _id: "613d384184c52bafdaaac527",
    thumbnail: "/images/library/the-64000-question.png",
    title: "The $64,000 Question",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Life is a series of asking questions and finding answers, so perhaps that’s why so many popular tv and radio shows—such as the famous 1960’s show after which this sermon is titled—have been based on asking questions. But what is the $64,000 question in the Bible?",
    categoryTags: ["#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=70gn-zMmESs",
  },
  {
    tagColors: [],
    _id: "6140c6c8baf4b8a1ed78a93b",
    thumbnail: "/images/library/the-antichrist-and-his-church.png",
    title: "The Antichrist and His Church",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Antichrist and His Churchby J Vernon McGee",
    categoryTags: ["#BR", "#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=9vBv1SieaTE",
  },
  {
    tagColors: [],
    _id: "613d2e9584c52bafdaaac50c",
    thumbnail: "/images/library/the-apostasy-has-arrived.png",
    title: "The Apostasy Has Arrived",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Peter, Jude, and others all predicted the coming apostasy. Dr. McGee said that what was a cloud the size of a man’s hand in the days of those men is in our day a raging storm.",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=95yCHcG520g",
  },
  {
    tagColors: [],
    _id: "613937ffe23d117056d1f30c",
    thumbnail: "/images/library/the-authority-of-missions.png",
    title: "The Authority for Missions",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Authority for Missions by J Vernon McGee",
    categoryTags: ["#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=Fi630drPNZQ",
  },
  {
    tagColors: [],
    _id: "6138f775e23d117056d1f2fe",
    thumbnail: "/images/library/watch/the-best-love.png",
    title: "The Best Love",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Best Love by J Vernon McGee",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=E76r2W5qbqI&t=0s",
  },
  {
    tagColors: [],
    _id: "6139083ce23d117056d1f303",
    thumbnail: "/images/library/watch/the-bitter-sweet-of-life.png",
    title: "The Bittersweet of Life",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Bittersweet of Life by J Vernon McGee",
    categoryTags: ["#BR", "#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=JgG8f1fl6DA",
  },
  {
    tagColors: [],
    _id: "613b8f8db01f85108898eeb9",
    thumbnail: "/images/library/bridegroom-and-the-bride-anticipation.png",
    title: "The Bridegroom and the Bride Anticipation",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Bridegroom and the Bride—Anticipation by J Vernon McGee",
    categoryTags: ["#OR", "#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=HOt8N_8mfZY",
  },
  {
    tagColors: [],
    _id: "6140c9c8baf4b8a1ed78a946",
    thumbnail: "/images/library/the-call-and-commision-line-of-isaiah.png",
    title: "The Call and Commission of Isaiah",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Call and Commission of Isaiah J Vernon McGee",
    categoryTags: ["#OR", "#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=t1kOVJrqUts",
  },
  {
    tagColors: [],
    _id: "6140cdb8baf4b8a1ed78a952",
    thumbnail: "/images/library/the-christian-conflict.png",
    title: "The Christian Conflict",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Christian Conflict by  J Vernon McGee",
    categoryTags: ["#YLW", "#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=euSJhL1OHaQ",
  },
  {
    tagColors: [],
    _id: "613d21777258c555c0886481",
    thumbnail:
      "/images/library/the-church-that-goes-through-the-great-tribulation.png",
    title: "The Church That Goes Through the Great Tribulation",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Do you believe the church will be raptured before the Tribulation? Well, so did Dr. McGee, but he said there will be a church that goes through the Tribulation. How is this possible?",
    categoryTags: ["#GR", "#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=b0aSn7GRNT4",
  },
  {
    tagColors: [],
    _id: "613d2fe784c52bafdaaac50e",
    thumbnail: "/images/library/the-country-preacher-who-came-to-town.png",
    title: "The Country Preacher Who Came to Town",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "If you had a message for the political, social, and religious leaders of the world, who would you send to deliver it? God chose a man from the back side of the desert, using the foolish to confound the wise.",
    categoryTags: ["#RD", "#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=iGYeVqHfTH4",
  },
  {
    tagColors: [],
    _id: "613d285884c52bafdaaac4fa",
    thumbnail: "/images/library/the-dark-side-of-love.png",
    title: "The Dark Side of Love",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Corrects our mistaken notion that God's love is a sentimental feeling rather than a deep concern for His own.",
    categoryTags: ["#RD", "#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=xGMB-zuBd1o",
  },
  {
    tagColors: [],
    _id: "613b8883b01f85108898eeb7",
    thumbnail: "/images/library/the-death-rattle-of-a-nation.png",
    title: "The Death Rattle of a Nation",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Death Rattle of a Nation by J Vernon McGee",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=XEJxdrmYatA",
  },
  {
    tagColors: [],
    _id: "61390594e23d117056d1f302",
    thumbnail: "/images/library/watch/the-drama-of-heaven-and-earth.png",
    title: "The Drama of Heaven And Earth",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Drama of Heaven And Earth by J Vernon McGee",
    categoryTags: ["#OR", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=jAxGgDTJkBU",
  },
  {
    tagColors: [],
    _id: "613d33e184c52bafdaaac519",
    thumbnail: "/images/library/the-entrance-exams-to-gods-university.png",
    title: "The Entrance Exams to God’s University",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "In his epistle, James enrolls the believer in the University of God. But there are entrance exams to be taken, and they’re not easy.",
    categoryTags: ["#BR", "#GN"],
    sermonUrl: "https://www.youtube.com/watch?v=7BE71-uCs8g",
  },
  {
    tagColors: [],
    _id: "613d2b5f84c52bafdaaac504",
    thumbnail: "/images/library/the-eyes-of-jesus.png",
    title: "The Eyes of Jesus",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "It's been said that the eyes are the gateway to the soul. What we see and watch can have a direct impact upon our lives. But the eyes can also reveal the soul of a person. What about Jesus, what would His eyes reveal?  ",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=gj3uHDkSIl0",
  },
  {
    tagColors: [],
    _id: "613d2b9a84c52bafdaaac505",
    thumbnail: "/images/library/the-feet-of-jesus.png",
    title: "The Feet of Jesus",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "For most people around the world the main mode of transportation is by foot. Jesus was no stranger to this form of transport as He walked from village to village and place to place throughout His ministry, but how important are the feet of Jesus? ",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=k0gUN49EJJs",
  },
  {
    tagColors: [],
    _id: "6140ce2abaf4b8a1ed78a954",
    thumbnail:
      "/images/library/the-fullness-of-the-spirit-worship-and-witness.png",
    title: "The Fullness of the Spirit: Worship & Witness",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "The Fullness of the Spirit: Worship & Witness by  J Vernon McGee",
    categoryTags: ["#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=1GfbafnSXJU",
  },
  {
    tagColors: [],
    _id: "6140d542baf4b8a1ed78a968",
    thumbnail: "/images/library/god-of-all-comfort.png",
    title: "The God of All Comfort",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=av-2WCt1_GE&t=45s",
  },
  {
    tagColors: [],
    _id: "61390e6ce23d117056d1f305",
    thumbnail: "/images/library/watch/the-gospel-in-the-gates-of-jerusalem.png",
    title: "The Gospel in the Gates of Jerusalem ",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Gospel in the Gates of Jerusalem by J Vernon McGee",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=pxjzaajGjmA",
  },
  {
    tagColors: [],
    _id: "6140d5f4baf4b8a1ed78a96a",
    thumbnail: "/images/library/the-gospel-in-the-gates-of-jerusalem-1.png",
    title: "The Gospel in the Gates of Jerusalem, Part 1",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Dr. McGee takes us on a tour around the ten gates of the city of Jerusalem in Nehemiah’s day and sees an application for each gate to our experiences as believers in Christ.",
    categoryTags: ["#OR", "#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=LNNaU31gHUY",
  },
  {
    tagColors: [],
    _id: "6140d589baf4b8a1ed78a969",
    thumbnail: "/images/library/the-gospel-in-the-gates-of-jerusalem-2.png",
    title: "The Gospel in the Gates of Jerusalem, Part 2",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Dr. McGee takes us on a tour around the ten gates of the city of Jerusalem in Nehemiah’s day and sees an application for each gate to our experiences as believers in Christ.",
    categoryTags: ["#OR", "#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=PATRkEeZuEs",
  },
  {
    tagColors: [],
    _id: "6140cab0baf4b8a1ed78a949",
    thumbnail: "/images/library/the-greates-love-story-ever-told.png",
    title: "The Greatest Love Story Ever Told",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Greatest Love Story Ever Told by  J Vernon McGee",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=nh-cPOYBQ0o",
  },
  {
    tagColors: [],
    _id: "6140c6f8baf4b8a1ed78a93c",
    thumbnail: "/images/library/the-greates-sermon-his-of-the-apostle-paul.png",
    title: "The Greatest Sermon of the Apostle Paul",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Greatest Sermon of the Apostle Paul J Vernon McGee",
    categoryTags: ["#OR", "#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=OcqTvNh8QMM",
  },
  {
    tagColors: [],
    _id: "613d350884c52bafdaaac51e",
    thumbnail: "/images/library/the-greatest-sin-in-all-the-world.png",
    title: "The Greatest Sin in All the World",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "The Scriptures list many sins that are considered awful. But is it possible to put one of them at the top and call it the greatest sin of all?",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=u2oJgsSC8Tk",
  },
  {
    tagColors: [],
    _id: "613d2bd384c52bafdaaac506",
    thumbnail: "/images/library/the-hands-of-jesus.png",
    title: "The Hands of Jesus",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "God reveals Himself to us through creation and His Word, but the greatest form of revelation is found in the person of Jesus Christ. So how did Jesus reveal the nature and character of God? In part, it’s through His nail-scarred hands.",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=k0gUN49EJJs",
  },
  {
    tagColors: [],
    _id: "613d24ad7258c555c0886488",
    thumbnail: "/images/library/the-holy-spirit-in-the-world.png",
    title: "The Holy Spirit in the World",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "What is the Holy Spirit's ministry today? Is He doing anything? Dr. McGee assures us that the Spirit is working in the world for the glory of God. ",
    categoryTags: ["#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=Hc2Uc3TN5DU",
  },
  {
    tagColors: [],
    _id: "6140c473baf4b8a1ed78a934",
    thumbnail: "/images/library/the-home-a-casualty-of-the-last-days.png",
    title: "The Home: A Casualty of the Last Days",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Home: A Casualty of the Last Days by J Vernon McGee",
    categoryTags: ["#PNK"],
    sermonUrl: "https://www.youtube.com/watch?v=TnYqyKXO94k",
  },
  {
    tagColors: [],
    _id: "6140c82abaf4b8a1ed78a940",
    thumbnail: "/images/library/the-lamb-and-the-lambs.png",
    title: "The Lamb and the Lambs",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Lamb and the Lambs J Vernon McGee",
    categoryTags: ["#GR", "#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=5WR6EVLdyeM",
  },
  {
    tagColors: [],
    _id: "613d18337258c555c0886474",
    thumbnail: "/images/library/the-loveliness-of-jesus.png",
    title: "The Loveliness of Jesus",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "We live in a dark world full of rebellion and hostility against the righteousness of God and His Word. But against that dark backdrop, God has provided a light in the Savior. The Scriptures reveal the beauty of His character as one who is compassionate to those who live in the hopelessness of sin.",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=h50xGxYQrGg",
  },
  {
    tagColors: [],
    _id: "613d36a384c52bafdaaac521",
    thumbnail: "/images/library/the-man-who-lived-before-he-was-born.png",
    title: "The Man Who Lived Before He was Born",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "What most people fail to understand about the birth of Jesus is that the story began long before the coming of a baby placed in a manger.",
    categoryTags: ["#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=MY81WinrsD4",
  },
  {
    tagColors: [],
    _id: "613d38a684c52bafdaaac528",
    thumbnail: "/images/library/the-man-in-glory.png",
    title: "The Man in the Glory",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "According to the Law of Moses, the High Priest would enter the Holy of Holies on the Day of Atonement to sprinkle blood on the Mercy Seat. He acted as a mediator between God and Israel. Today, we also have a High Priest: Jesus Christ.",
    categoryTags: ["#PPL", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=TsWsWKiEyeU",
  },
  {
    tagColors: [],
    _id: "6140d35fbaf4b8a1ed78a962",
    thumbnail: "/images/library/the-man-the-devil-try-to-brainwash.png",
    title: "The Man the Devil Tried to Brainwash",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "(Job 1, 2) On any given day of the week the media reports on stories of violence, war, natural disasters, and the devastation to human life caused by famine and illness. So why does suffering occur in the lives of God’s children?",
    categoryTags: ["#BR", "#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=FKhtFKt7Q5o",
  },
  {
    tagColors: [],
    _id: "61393f13e23d117056d1f30f",
    thumbnail: "/images/library/the-message-of-the-silent-years.png",
    title: "The Message of the Silent Years",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Message of the Silent Years by J Vernon McGee",
    categoryTags: ["#RD", "#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=vAXzzLK2O_s",
  },
  {
    tagColors: [],
    _id: "613d245e7258c555c0886487",
    thumbnail: "/images/library/the-message-of-the-silent-years.png",
    title: "The Message of the Silent Years",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Between the birth of Jesus and His baptism, Scripture seems to be silent. Yet upon closer inspection, we find a wealth of information about the activities and events that occurred during the formative years of Jesus’ life.",
    categoryTags: ["#BL", "#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=vAXzzLK2O_s",
  },
  {
    tagColors: [],
    _id: "6140c1cebaf4b8a1ed78a92e",
    thumbnail: "/images/library/the-millenial-temple-why-the-sacrifices.png",
    title: "The Millennial Temple: Why the Sacrifices?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "During the Millennium there will be built a new temple with a return to the sacrificial system. But if Christ’s death on the cross removed the need for sacrifices for sins, why is there a return to the sacrificial system during the Millennium?",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=FRQ7BQDqKO8",
  },
  {
    tagColors: [],
    _id: "6140c907baf4b8a1ed78a943",
    thumbnail: "/images/library/the-millenium-versus-the-great-society-1.png",
    title: "The Millennium Versus the Great Society, Part 1",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "The Millennium Versus the Great Society, Part 1 J Vernon McGee",
    categoryTags: ["#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=xrM80WqVAK0",
  },
  {
    tagColors: [],
    _id: "6140c8cdbaf4b8a1ed78a942",
    thumbnail: "/images/library/the-millenium-versus-the-great-society-2.png",
    title: "The Millennium Versus the Great Society, Part 2",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "The Millennium Versus the Great Society, Part 2 J Vernon McGee",
    categoryTags: ["#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=jgcS9fTMJ0A",
  },
  {
    tagColors: [],
    _id: "6140c86ebaf4b8a1ed78a941",
    thumbnail: "/images/library/the-millenium-versus-the-great-society-3.png",
    title: "The Millennium Versus the Great Society, Part 3",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "The Millennium Versus the Great Society, Part 3 J Vernon McGee",
    categoryTags: ["#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=bUA01hP-kOA",
  },
  {
    tagColors: [],
    _id: "613d1f487258c555c088647b",
    thumbnail: "/images/library/the-millenium-what-where-when-who.png",
    title: "The Millennium: What? Where? When? How? Who?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Revelation 20 speaks of the thousand-year reign of Christ on the earth known as the Millennium. But it’s in the prophecies of Isaiah that we must turn to view a detailed picture of what those days will be like.",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=b_7J3kPqjD0",
  },
  {
    tagColors: [],
    _id: "613d25eb7258c555c088648d",
    thumbnail: "/images/library/the-missle-from-outter-space.png",
    title: "The Missile From Outer Space",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Have you ever seen a UFO? Well, there was a man who saw things flying through the air, but he was told exactly what they were. The man was the prophet Zechariah who on one night had ten visions given to him by God. ",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=o9tU9nKsm4U",
  },
  {
    tagColors: [],
    _id: "613900d4e23d117056d1f2ff",
    thumbnail: "/images/library/watch/the-mother-love-of-the-father-god.png",
    title: "The Mother Love of the Father God",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Mother Love of the Father God by J Vernon McGee",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=3qUL1st-uPs",
  },
  {
    tagColors: [],
    _id: "613d224a7258c555c0886483",
    thumbnail: "/images/library/the-new-testament-church.png",
    title: "The New Testament Church",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "What is the New Testament Church? Can we find it in the in-fighting of the Corinthian church or the legalism of the Galatian church? Or is it something else altogether?",
    categoryTags: ["#GR", "#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=1tg0h6SzGPQ",
  },
  {
    tagColors: [],
    _id: "613d146bd8636f51a068a526",
    thumbnail: "/images/library/the-next-happening-in-the-program-of-God.png",
    title: "The Next Happening in the Program of God",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "God is following a plan. This truth is revealed in the numerous prophecies recorded in the Scriptures. Most have already been fulfilled, but there are still many waiting for the day of their fulfillment, particularly those dealing with the Second Coming of Christ.",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=-fTrE5wLpr4",
  },
  {
    tagColors: [],
    _id: "61393a19e23d117056d1f30d",
    thumbnail: "/images/library/the-only-psalm.png",
    title: "The Only Psalm",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Only Psalm by J Vernon McGee",
    categoryTags: ["#RD", "#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=6foEo9Mittw",
  },
  {
    tagColors: [],
    _id: "61393ba6e23d117056d1f30e",
    thumbnail: "/images/library/the-potter-and-the-clay.png",
    title: "The Potter and the Clay",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Potter and the Clay  by J Vernon McGee",
    categoryTags: ["#RD", "#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=iZkUFoLKi-A",
  },
  {
    tagColors: [],
    _id: "613904d0e23d117056d1f300",
    thumbnail: "/images/library/the-power-of-negative-thinking.png",
    title: "The Power of Negative Thinking",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Power of Negative Thinking by J Vernon McGee",
    categoryTags: ["#GRN", "YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=MBwmomcuXg4",
  },
  {
    tagColors: [],
    _id: "6140c3c6baf4b8a1ed78a932",
    thumbnail: "/images/library/the-prophet-who-used-television.png",
    title: "The Prophet Who Used Television",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Prophet Who Used Television by J Vernon McGee",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=EGT9hzjg-lg",
  },
  {
    tagColors: [],
    _id: "6140d09bbaf4b8a1ed78a95b",
    thumbnail: "/images/library/the-psalm-of-an-old-shepherd.png",
    title: "The Psalm of an Old Shepherd",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Psalm of an Old Shepherd by  J Vernon McGee",
    categoryTags: ["#RD", "#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=90BM9V7fV40",
  },
  {
    tagColors: [],
    _id: "6140c5d6baf4b8a1ed78a938",
    thumbnail: "/images/library/the-sanctuary-of-the-soul.png",
    title: "The Sanctuary of the Soul",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Sanctuary of the Soul by J Vernon McGee",
    categoryTags: ["#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=kJ4DVibGJY0",
  },
  {
    tagColors: [],
    _id: "6140d42ebaf4b8a1ed78a965",
    thumbnail: "/images/library/the-secret-weapon-of-spiritual-warefare.png",
    title: "The Secret Weapon of Spiritual Warfare",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "(2 Corinthians 10) We’re at war with spiritual beings, but what weapons do we have to fight off the attacks? We’ll discover not only what they are, but how to use them in our daily warfare in the heavenlies.",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=HSTYkHwU2qU",
  },
  {
    tagColors: [],
    _id: "613d252f7258c555c088648a",
    thumbnail: "/images/library/the-secret-of-power.png",
    title: "The Secret of Power",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Why are we impotent against the onslaught of evil that overruns our world? We find the secret of power in this unexpected place in the Old Testament.",
    categoryTags: ["#PPL", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=dmb567xFm3k",
  },
  {
    tagColors: [],
    _id: "613d13e3d8636f51a068a525",
    thumbnail: "/images/library/the-shepherd-and-the-sheep.png",
    title: "The Shepherd and the Sheep",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "One of the most tender ways God expresses His love and care for us is by describing Himself as a Shepherd and each of us as His sheep. But who exactly is counted among “His” sheep? And what exactly is He trying to tell us? Join Dr. McGee for a  meaningful tour through the pages of Scripture (including a final stop in Psalm 23) as he answers these questions and more.",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=EqHMEJ6iOTc",
  },
  {
    tagColors: [],
    _id: "6140d3e6baf4b8a1ed78a964",
    thumbnail: "/images/library/the-strange-providences-of-god.png",
    title: "The Strange Providences of God",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "(Esther) What determines the events in our lives? Is it chance? Is it our choices? What we’ll discover that the foundation of the Bible is that God’s providence is always at work in every event.",
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=ibkJOrfTlTc",
  },
  {
    tagColors: [],
    _id: "613d2f9184c52bafdaaac50d",
    thumbnail: "/images/library/the-swang-song-of-simon.png",
    title: "The Swan Song of Simon",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Peter, in his deathbed statement, tells us to have confidence in our faith, avoid the apostasy brought by false teachers, and be encouraged that God is in control.",
    categoryTags: ["#OR", "#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=Nr8r1ZLcigo",
  },
  {
    tagColors: [],
    _id: "613d293a84c52bafdaaac4fd",
    thumbnail: "/images/library/the-tears-of-god.png",
    title: "The Tears of God",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Three incidents in the ministry of the Lord Jesus Christ inform us that He wept, and those tears reveal the heart of God.",
    categoryTags: ["#RD", "#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=uptuDmcfgCQ",
  },
  {
    tagColors: [],
    _id: "613d1fe47258c555c088647c",
    thumbnail: "/images/library/the-time-of-armagedon.png",
    title: "The Time of Armageddon",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Although history has labeled two wars in the last century as “world wars,” the true world war will occur as the days of the Great Tribulation rise to a fevered pitch during the war of Armageddon.",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=BMyvUas7aoc",
  },
  {
    tagColors: [],
    _id: "613a6b31a749fb4edf1205b8",
    thumbnail: "/images/library/the-times-of-the-gentiles.png",
    title: "The Times of the Gentiles",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Times of the Gentiles by J Vernon McGee",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=aXtq07JOVQ8",
  },
  {
    tagColors: [],
    _id: "613d394284c52bafdaaac52a",
    thumbnail: "/images/library/the-times-of-the-gentiles.png",
    title: "The Times of the Gentiles",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "For almost a millennium, the children of Israel possessed Palestine. But because of their disobedience, they were taken away into captivity. That was the beginning of a new period in which Jerusalem would be “trampled by the Gentiles until the times of the Gentiles be fulfilled.”",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=aXtq07JOVQ8&t=1s",
  },
  {
    tagColors: [],
    _id: "6140ca6cbaf4b8a1ed78a948",
    thumbnail: "/images/library/the-unfinished-sufferings-of-christ.png",
    title: "The Unfinished Sufferings of Christ",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "The Unfinished Sufferings of Christ by  J Vernon McGee",
    categoryTags: ["#BR", "#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=jNhQvzlvaDE",
  },
  {
    tagColors: [],
    _id: "613d1362d8636f51a068a524",
    thumbnail: "/images/library/the-vine-and-the-brahes.png",
    title: "The Vine and the Branches",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Jesus uses the illustration of the vine and the branches to picture His relationship to the church. Dr. McGee brings out the practical teaching for believers today.",
    categoryTags: ["#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=D0WAyVHdOiE",
  },
  {
    tagColors: [],
    _id: "613d26bf7258c555c0886490",
    thumbnail: "/images/library/the-law-of-god-and-the-way-of-man.png",
    title: "The Word of God and the Way of Man",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "What happens when the way that seems right to man is confronted by the Word of God and found to be the wrong way? Haggai had to deal with such a situation with his own people after their return to Jerusalem after 70 years of captivity. ",
    categoryTags: ["#BL", "#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=5o6AfVdxG4w",
  },
  {
    tagColors: [],
    _id: "6140c777baf4b8a1ed78a93d",
    thumbnail: "/images/library/these-three.png",
    title: "These Three",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "These Three J Vernon McGee",
    categoryTags: ["#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=3YKcZTzVCiY",
  },
  {
    tagColors: [],
    _id: "6140cea8baf4b8a1ed78a955",
    thumbnail: "/images/library/this-is-the-house-that-god-built.png",
    title: "This is the House That God Built",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "This is the House That God Built by  J Vernon McGee",
    categoryTags: ["#Bl"],
    sermonUrl: "https://www.youtube.com/watch?v=08dqaD3pgQw",
  },
  {
    tagColors: [],
    _id: "613d332584c52bafdaaac518",
    thumbnail: "/images/library/translating-book-learning-into-life.png",
    title: "Translating Book Learning Into Life",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Despite all the different Bible translations available now, there is one that is superior to all the others—but it can’t be purchased in your local Christian bookstore.",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=K7pXmNznrZw",
  },
  {
    tagColors: [],
    _id: "6140c33dbaf4b8a1ed78a931",
    thumbnail: "/images/library/watchman-what-of-the-night.png",
    title: "Watchman, What of the Night?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      'Jesus loves you! J Vernon McGee teaches us about  "Angels With Dirty Faces" in this Sunday Sermon in a way that you can easily understand. Thru the Bible Radio.',
    categoryTags: ["#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=bI7GyoOhiPU",
  },
  {
    tagColors: [],
    _id: "6140cdfebaf4b8a1ed78a953",
    thumbnail: "/images/library/we-are-going-to-a-wedding.png",
    title: "We Are Going to a Wedding",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "We Are Going to a Wedding by  J Vernon McGee",
    categoryTags: ["#RD", "#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=6Tu_herVFf8",
  },
  {
    tagColors: [],
    _id: "613d359c84c52bafdaaac520",
    thumbnail: "/images/library/what-about-angels.png",
    title: "What About Angels?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Angels are mentioned in nearly every book of the Bible. But what do you know about these heavenly creatures?",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=v1bE_OZNBdU",
  },
  {
    tagColors: [],
    _id: "613d277f7258c555c0886491",
    thumbnail:
      "/images/library/what-can-believers-do-in-days-of-of-apostasy.png",
    title: "What Can Believers Do in Days of Apostasy?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "We are living in days of apostasy, and the most severe attack on the Word of God, the Christian faith, and the church is coming from within the church itself. What can believers do about it? ",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=e0J9GxLXtFU",
  },
  {
    tagColors: [],
    _id: "6140cd3ebaf4b8a1ed78a950",
    thumbnail: "/images/library/what-do-you-do-with-your-future.png",
    title: "What Do You Do With Your Future?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "What Do You Do With Your Future? by  J Vernon McGee",
    categoryTags: ["#YLW", "#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=YbXttuP2-8w",
  },
  {
    tagColors: [],
    _id: "613911b6e23d117056d1f307",
    thumbnail: "/images/library/what-do-you-do-with-your-past.png",
    title: "What Do You Do With Your Past?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "What Do You Do With Your Past? by J Vernon McGee",
    categoryTags: ["#GR", "#RD"],
    sermonUrl: "https://www.youtube.com/watch?v=ItfvV_ecAL0",
  },
  {
    tagColors: [],
    _id: "613d2aa484c52bafdaaac502",
    thumbnail: "/images/library/what-does-god-look-like.png",
    title: "What Does God Look Like?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "How can one describe someone who has never been seen? Although we can’t know what God looks like, we can allow others to see a glimpse of Him—through the way we live our lives.",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=SlgmEH-5-_k",
  },
  {
    tagColors: [],
    _id: "613d1d3b7258c555c0886479",
    thumbnail: "/images/library/what-and-where-is-heaven.png",
    title: "What and Where is Heaven?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Most people want to go to heaven, but few understand what it’s really like, nor do they have any idea where it is. But Scripture provides us with some wonderful clues.",
    categoryTags: ["#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=ZrDEUYfCIfQ",
  },
  {
    tagColors: [],
    _id: "613d1c817258c555c0886477",
    thumbnail: "/images/library/what-is-doctrine.png",
    title: "What is Doctrine?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "In order to properly study the Bible, you must understand several foundational truths. Understanding doctrine helps you grasp the Bible’s biggest themes and see the big picture before studying specifics. Get a good perspective of God’s Word here. ",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=nap8_IZzxtw",
  },
  {
    tagColors: [],
    _id: "613d329184c52bafdaaac516",
    thumbnail: "/images/library/what-is-worldliness.png",
    title: "What is Worldliness?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Wisdom comes from two places—from above and from below. The Epistle of James has a great deal to say about the wisdom that is heavenly and that which is worldly.",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=5O8z7zMCJ1c",
  },
  {
    tagColors: [],
    _id: "613d31e984c52bafdaaac513",
    thumbnail: "/images/library/what-is-your-life.png",
    title: "What is Your Life?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Will you be here tomorrow, next week, next month, or next year? No one knows for sure, because the Bible says that our lives are like mist—here today and gone tomorrow. So what should our attitude be today in light of the uncertainty of tomorrow?",
    categoryTags: ["#CYN", "#YLW"],
    sermonUrl: "https://www.youtube.com/watch?v=uC1Vg3kPOps",
  },
  {
    tagColors: [],
    _id: "613d175d7258c555c0886472",
    thumbnail: "/images/library/what-is-the-world-coming-to.png",
    title: "What is the World Coming To",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "In Matthew 24, Jesus said that the beginning of sorrows for the Great Tribulation will be filled with famines, pestilence, and earthquakes. But long before Jesus spoke these words, David prophesied about these things in Psalm 2.",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=zJMSP1BYOuY",
  },
  {
    tagColors: [],
    _id: "6140ca28baf4b8a1ed78a947",
    thumbnail: "/images/library/what-the-well-dressed-christian-will-wear.png",
    title: "What the Well-Dressed Christian Will Wear",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "What the Well-Dressed Christian Will Wear by  J Vernon McGee",
    categoryTags: ["#YLW", "#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=hEWBxLuzles",
  },
  {
    tagColors: [],
    _id: "613d25677258c555c088648b",
    thumbnail: "/images/library/when-christ-returns-to-jerusalem.png",
    title: "When Christ Returns in Triumph to Jerusalem",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Christ’s first coming wasn’t for judgment, but to provide a way of peace, reconciling men to God. But His second coming will be for the judgment of all who have forsaken the free offering of salvation that He came to provide the first time.",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=cSnaefGFhNU",
  },
  {
    tagColors: [],
    _id: "61391605e23d117056d1f309",
    thumbnail: "/images/library/when-death-should-not-take-a-holiday.png",
    title: "When Death Should Not Take a Holiday",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "When Death Should Not Take a Holiday by J Vernon McGee",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=EF8EUT0PT2w",
  },
  {
    tagColors: [],
    _id: "6140c93cbaf4b8a1ed78a944",
    thumbnail: "/images/library/when-god-flexes-his-muscles.png",
    title: "When God Flexes His Muscles",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "When God Flexes His Muscles J Vernon McGee",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=MSvyzVRJv9g",
  },
  {
    tagColors: [],
    _id: "613d26307258c555c088648e",
    thumbnail: "/images/library/when-jesus-went-to-a-funeral.png",
    title: "When Jesus Went to a Funeral",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Usually a funeral is a time of mourning and sorrow, but not with Jesus in attendance. The Bible records three times when Jesus attended a funeral, and each time He turned sorrow into joy and mourning into praise.",
    categoryTags: ["#RD", "#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=6HLOLIzB8b0",
  },
  {
    tagColors: [],
    _id: "6140cbf1baf4b8a1ed78a94d",
    thumbnail: "/images/library/when-paul-changed-his-bookkeeping-system.png",
    title: "When Paul Changed His Bookkeeping System",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "When Paul Changed His Bookkeeping System by  J Vernon McGee",
    categoryTags: ["#RD", "#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=W7dyjVcUTqE",
  },
  {
    tagColors: [],
    _id: "6140cf01baf4b8a1ed78a956",
    thumbnail: "/images/library/when-paul-prayed.png",
    title: "When Paul Prayed",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "When Paul Prayed by  J Vernon McGee",
    categoryTags: ["#BL", "#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=-gSiWaa4OrM",
  },
  {
    tagColors: [],
    _id: "61391879e23d117056d1f30a",
    thumbnail: "/images/library/when-surrender-is-victory.png",
    title: "When Surrender Is Victory",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "When Surrender Is Victory by J Vernon McGee",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=pcKvzxc2xIc",
  },
  {
    tagColors: [],
    _id: "613d354284c52bafdaaac51f",
    thumbnail: "/images/library/where-is-christ-and-what-is-he-doing.png",
    title: "Where is Christ Now and What is He Doing?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "After Jesus’ ascension, we’re not told about His activities or where He was going. However, the Scriptures are not silent!",
    categoryTags: ["#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=t4oGsDj6_ds",
  },
  {
    tagColors: [],
    _id: "613d2a1a84c52bafdaaac500",
    thumbnail: "/images/library/where-is-god-and-what-does-he-do.png",
    title: "Where is God and What Does He Do?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "God is omnipresent, omnipotent and omniscient. He is everywhere, and He indwells believers. What He does depends on what we allow Him to do through us.",
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=1rWggNCp0Ao",
  },
  {
    tagColors: [],
    _id: "613d21097258c555c0886480",
    thumbnail: "/images/library/whither-the-church-woe-or-woa.png",
    title: "Whither the Church: Woe! or Whoa!",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Dr. McGee stated, “Jude contains a vivid and dramatic description of the apostates who have taken over the church today.” Is revival possible? Or will it be revolution? ",
    categoryTags: ["#GR", "#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=NEEza9sq-X0",
  },
  {
    tagColors: [],
    _id: "613d24f47258c555c0886489",
    thumbnail: "/images/library/who-is-the-holy-spirit.png",
    title: "Who is the Holy Spirit?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Many believers and dedicated church-goers really have little to no knowledge about the third member of the trinity—what He does, where He is, and why it's so important to have Him working in our lives today. ",
    categoryTags: ["#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=8kOZ-ddF8qc",
  },
  {
    tagColors: [],
    _id: "613d22e27258c555c0886485",
    thumbnail: "/images/library/why-did-god-become-a-man.png",
    title: "Why Did God Become a Man?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "In his epistle to the Philippians, Paul says that Jesus “made Himself of no reputation, taking the form of a bondservant, and coming in the likeness of men.” This begs the question, why would God the Son leave His heavenly dwelling and in humility take on human nature?",
    categoryTags: ["#BL", "#PPL"],
    sermonUrl: "https://www.youtube.com/watch?v=HCS2Qw-szl8",
  },
  {
    tagColors: [],
    _id: "61390ca0e23d117056d1f304",
    thumbnail: "/images/library/watch/why-do-gods-people-suffer.png",
    title: "Why Do God's People Suffer?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Why Do God's People Suffer? by J Vernon McGee",
    categoryTags: ["#BR", "#GR"],
    sermonUrl: "https://www.youtube.com/watch?v=91WHfiX_5hM",
  },
  {
    tagColors: [],
    _id: "6140d301baf4b8a1ed78a961",
    thumbnail: "/images/library/why-do-gods-people-suffer.png",
    title: "Why Do God's People Suffer?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "(Job 1, 2) On any given day of the week the media reports on stories of violence, war, natural disasters, and the devastation to human life caused by famine and illness. So why does suffering occur in the lives of God’s children?",
    categoryTags: ["#BR", "#CYN"],
    sermonUrl: "https://www.youtube.com/watch?v=91WHfiX_5hM&t=1s",
  },
  {
    tagColors: [],
    _id: "6139339ee23d117056d1f30b",
    thumbnail: "/images/library/why-god-hated-esau.png",
    title: "Why God Hated Esau",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Why God Hated Esau by J Vernon McGee",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=3f2N_Xwbrys",
  },
  {
    tagColors: [],
    _id: "613d1cd87258c555c0886478",
    thumbnail:
      "/images/library/why-i-believe-the-coming-of-the-lord-is-near.png",
    title: "Why I Believe the Coming of the Lord is Near",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "From the early 1970s to the countdown to the 21st century, there was an ever-increasing, feverish call for the return of Christ at any moment. Although things have calmed down, the question still remains: When will Christ return?",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=6HcpkhV8_jI",
  },
  {
    tagColors: [],
    _id: "613d345484c52bafdaaac51a",
    thumbnail: "/images/library/why-israel-must-return-to-palestine.png",
    title: "Why Israel Must Return to Palestine",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Do the promises in Scripture of future restoration refer to the church, or will God’s people possess the land of Israel again? What does the Bible really say about God’s plan to fulfill His promise?",
    categoryTags: ["#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=Fl5IIBN3IzY",
  },
  {
    tagColors: [],
    _id: "613d21d97258c555c0886482",
    thumbnail:
      "/images/library/why-jesus-church-will-not-go-through-the-great-tribulation.png",
    title: "Why Jesus’ Church Will Not Go Through the Tribulation",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "In recent years, there has been a flurry of debate over the issue of the end times—specifically, the timing of the Rapture. Will it be before, during, or after the Tribulation?",
    categoryTags: ["#GR", "#OR"],
    sermonUrl: "https://www.youtube.com/watch?v=3NFQBq9qB-Q",
  },
  {
    tagColors: [],
    _id: "6140d269baf4b8a1ed78a960",
    thumbnail: "/images/library/why-the-gospel-is-not-preached-today.png",
    title: "Why the Gospel is Not Preached Today",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "(Galatians 1:6-12) What is the gospel? Is it being preached in our churches today?",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=GNwEIDIbRiA",
  },
  {
    tagColors: [],
    _id: "613d1bde7258c555c0886476",
    thumbnail: "/images/library/why-the-resurrection-changes-everything.png",
    title: "Why the Resurrection Changes Everything",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      'If we believe “Christ died for our sins according to the Scriptures … was buried and that He rose again the third day," how should it change the way we live? Dr. McGee walks us through three  things the resurrection of Jesus confirms—the accuracy of the Word of God, the authority of the Lord Jesus Christ, and the promise of an eternal future with Him—and shows how these facts can and should change our day to day lives.',
    categoryTags: ["#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=VtHZolanv1g",
  },
  {
    tagColors: [],
    _id: "613d25af7258c555c088648c",
    thumbnail: "/images/library/will-babylon-be-rebuilt.png",
    title: "Will Babylon Be Rebuilt?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Scripture speaks of a woman arrayed in purple and scarlet, and on her forehead is written, “Mystery, Babylon the Great.” An angel explains to John that the woman “is that great city which reigns over the kings of the earth.” Some believe that this is a picture of the rebuilding of the great city of Babylon. ",
    categoryTags: ["#OR", "#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=q_AD97riyo0",
  },
  {
    tagColors: [],
    _id: "613d38f684c52bafdaaac529",
    thumbnail: "/images/library/will-everyone-ultimately-go-to-heaven.png",
    title: "Will Everyone Ultimately Go to Heaven?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "An overwhelming majority of people today believe that they will go to heaven. Some even believe that one day all people of all time will dwell in the presence of God, and they claim to have Scriptural support for this theory. But do they?",
    categoryTags: ["#CYN", "#GN"],
    sermonUrl: "https://www.youtube.com/watch?v=vYxmGHsVhG4",
  },
  {
    tagColors: [],
    _id: "613d20aa7258c555c088647f",
    thumbnail: "/images/library/will-there-be-total-apostasy-in-the-church.png",
    title: "Will There Be a Total Apostasy of the Church?",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description:
      "Many NMany New Testament writers spoke of the apostasy entering the church in their days. Today we are still seeing the apostasy of the church grow. But will there be a day when every church has turned away from the living and true God?",
    categoryTags: ["#BR"],
    sermonUrl: "https://www.youtube.com/watch?v=Yt5-ZzyMkC0",
  },
  {
    tagColors: [],
    _id: "6140c522baf4b8a1ed78a936",
    thumbnail: "/images/library/womens-place-in-the-local-church.png",
    title: "Women's Place in the Local Church",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "Women's Place in the Local Church by J Vernon McGee",
    categoryTags: ["#PNK"],
    sermonUrl: "https://www.youtube.com/watch?v=DTyOwnFpcRg",
  },
  {
    tagColors: [],
    _id: "613b91dcb01f85108898eeba",
    thumbnail: "/images/library/you-are-a-catholic-priest.png",
    title: "You Are a Catholic Priest",
    userId: "614e3c284613d4162ef5435d",
    by: "J Vernon McGee",
    reviews: [],
    stars: [],
    description: "You Are a Catholic Priest by J Vernon McGee",
    categoryTags: ["#GR", "#BL"],
    sermonUrl: "https://www.youtube.com/watch?v=FTXMYwjJjNg",
  },
];
