module.exports = story = [
  {
    id: "dgsfg",
    content: "This is a random quote LIGHT BLUE",
    by: "#MLFDL-S-DG",
    background:
      "linear-gradient(120deg, rgba(0,232,238,1) 0%, rgba(235,2,2,1) 100%)",
    tags: ["#LBL", "#BR"],
    approves: [],
    disapproves: ["dsds", "dsgds", "sgds", "gsgsgr"],
    comments: [
      {
        id: "dsdsweg",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Light Blue 1`,
      },
      {
        id: "dsd45s",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Light Blue 2`,
      },
      {
        id: "dsds79879",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Light Blue 3`,
      },
      {
        id: "dsd3479976s",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Light Blue 4`,
      },
      {
        id: "dsds12421",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Light Blue 5`,
      },
      {
        id: "dsd42353256s",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Light Blue 6`,
      },
      {
        id: "dsds6765754",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Light Blue 7`,
      },
      {
        id: "dsd23905hfs",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Light Blue 8`,
      },
      {
        id: "dsds425gds",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Light Blue 9`,
      },
      {
        id: "ds44625fefdds",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Light Blue 10`,
      },
    ],
  },
  {
    id: "dgsf32g",
    content: "This is a random quote YELLOW",
    by: "User Name",
    background:
      "linear-gradient(120deg, rgba(255,208,2,1) 0%, rgba(224,67,241,1) 100%)",
    tags: ["#YLW", "#BR"],
    approves: [],
    disapproves: ["dsds", "dsgds", "sgds", "gsgsgr"],
    comments: [
      {
        id: "dsdsweg",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Yellow 1`,
      },
    ],
  },
  {
    id: "dg2334sfg",
    content: "This is a random quote PURPLE",
    by: "User Name",
    background:
      "linear-gradient(120deg, rgba(153,2,237,1) 0%, rgba(10,207,213,1) 100%)",
    tags: ["#PPL", "#BR"],
    approves: [],
    disapproves: ["dsds", "dsgds", "sgds", "gsgsgr"],
    comments: [
      {
        id: "dsdsweg",
        userId: "gdsgdsgds",
        userAvatar: "/images/temporary/Avatar4.png",
        userSignature: "#ASKTH",
        content: `Purple 1`,
      },
    ],
  },
];
