module.exports = stories = [
  {
    id: "iufwee",
    userId: "dfdsfd",
    userAvatar: "/images/temporary/Avatar4.png",
    stories: [
      {
        content: "This is a random quote LIGHT BLUE",
        by: "User Name",
        background:
          "linear-gradient(120deg, rgba(0,232,238,1) 0%, rgba(235,2,2,1) 100%)",
        tags: ["#LBL", "#BR"],
        approves: [],
        disapproves: ["dsds", "dsgds", "sgds", "gsgsgr"],
        comments: [
          {
            id: "dsdsweg",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Light Blue 1`,
          },
          {
            id: "dsd45s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Light Blue 2`,
          },
          {
            id: "dsds79879",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Light Blue 3`,
          },
          {
            id: "dsd3479976s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Light Blue 4`,
          },
          {
            id: "dsds12421",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Light Blue 5`,
          },
          {
            id: "dsd42353256s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Light Blue 6`,
          },
          {
            id: "dsds6765754",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Light Blue 7`,
          },
          {
            id: "dsd23905hfs",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Light Blue 8`,
          },
          {
            id: "dsds425gds",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Light Blue 9`,
          },
          {
            id: "ds44625fefdds",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Light Blue 10`,
          },
        ],
      },
      {
        content: "This is a random quote YELLOW",
        by: "User Name",
        background:
          "linear-gradient(120deg, rgba(255,208,2,1) 0%, rgba(224,67,241,1) 100%)",
        tags: ["#YLW", "#BR"],
        approves: [],
        disapproves: ["dsds", "dsgds", "sgds", "gsgsgr"],
        comments: [
          {
            id: "dsdsweg",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Yellow 1`,
          },
        ],
      },
      {
        content: "This is a random quote PURPLE",
        by: "User Name",
        background:
          "linear-gradient(120deg, rgba(153,2,237,1) 0%, rgba(10,207,213,1) 100%)",
        tags: ["#PPL", "#BR"],
        approves: [],
        disapproves: ["dsds", "dsgds", "sgds", "gsgsgr"],
        comments: [
          {
            id: "dsdsweg",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Purple 1`,
          },
        ],
      },
    ],
  },
  {
    id: "iufwe234e",
    userId: "df324dsfd",
    userAvatar: "/images/temporary/Avatar4.png",
    stories: [
      {
        content: "This is a random quote RED",
        by: "User Name",
        background:
          "linear-gradient(120deg, rgba(238,3,3,1) 0%, rgba(10,125,213,1) 100%)",
        tags: ["#RD", "#BR"],
        approves: ["fds", "rgrw"],
        disapproves: [],
        comments: [],
      },
    ],
  },
  {
    id: "iufwesf9340se",
    userId: "dfddsvsfd",
    userAvatar: "/images/temporary/Avatar4.png",
    stories: [
      {
        content: "This is a random quote PINK",
        by: "User Name",
        background:
          "linear-gradient(90deg, rgba(40,30,210,1) 0%, rgba(2,212,255,1) 100%)",
        tags: ["#PNK", "#BR"],
        approves: [],
        disapproves: ["gsgsgr"],
        comments: [
          {
            id: "dsdsweg",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Pink 1`,
          },
          {
            id: "dsd45s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Pink 2`,
          },
          {
            id: "dsds79879",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Pink 3`,
          },
          {
            id: "dsd3479976s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Pink 4`,
          },
          {
            id: "dsds12421",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Pink 5`,
          },
          {
            id: "dsd42353256s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Pink 6`,
          },
          {
            id: "dsds6765754",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Pink 7`,
          },
          {
            id: "dsd23905hfs",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Pink 8`,
          },
          {
            id: "dsds425gds",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Pink 9`,
          },
          {
            id: "ds44625fefdds",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Pink 10`,
          },
        ],
      },
    ],
  },
  {
    id: "iufwe85858e",
    userId: "dfdsfd",
    userAvatar: "/images/temporary/Avatar4.png",
    stories: [
      {
        content: "This is a random quote GREEN",
        by: "User Name",
        background:
          "linear-gradient(120deg, rgba(0,171,22,1) 0%, rgba(5,188,227,1) 100%)",
        tags: ["#GN", "#BR"],
        approves: [],
        disapproves: ["dsds", "dsgds", "sgds", "gsgsgr"],
        comments: [
          {
            id: "dsdsweg",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Green 1`,
          },
        ],
      },
      {
        content: "This is a random quote ORANGE",
        by: "User Name",
        background:
          "linear-gradient(120deg, rgba(255,73,0,1) 0%, rgba(160,5,227,1) 100%)",
        tags: ["#OR", "#BR"],
        approves: ["gsg", "dgds", "dgs", "sdgs"],
        disapproves: ["dsds", "dsgds", "sgds", "gsgsgr"],
        comments: [],
      },
    ],
  },
  {
    id: "iufw3333ee",
    userId: "dfdsfd",
    userAvatar: "/images/temporary/Avatar4.png",
    stories: [
      {
        content: "This is a random quote BLACK",
        by: "User Name",
        background:
          "linear-gradient(120deg, rgba(37,36,36,1) 0%, rgba(57,60,88,1) 100%)",
        tags: ["#BLK", "#BR"],
        approves: [],
        disapproves: ["dsds", "dsgds", "sgds", "gsgsgr"],
        comments: [],
      },
      {
        content:
          "This is a random quote BROWN This is a random quote BROWN This is a random quote BROWN This is a random quote BROWN This is a random quote BROWN This is a random quote BROWN This is a random quote BROWN This is a random quote BROWN This is a random quote BROWN This is a random quote BROWN",
        by: "User Name",
        background:
          "linear-gradient(120deg, rgba(150,75,0,1) 0%, rgba(31,0,0,1) 100%)",
        tags: ["#BR", "#BR"],
        approves: ["gweg", "egw"],
        disapproves: ["dsds"],
        comments: [
          {
            id: "dsdsweg",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Brown 1`,
          },
          {
            id: "dsd45s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `brown 2`,
          },
          {
            id: "dsds79879",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Brown 3`,
          },
          {
            id: "dsd3479976s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Brown 4`,
          },
          {
            id: "dsds12421",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Brown 5`,
          },
          {
            id: "dsd42353256s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Brown 6`,
          },
          {
            id: "dsds6765754",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Brown 7`,
          },
          {
            id: "dsd23905hfs",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Brown 8`,
          },
          {
            id: "dsds425gds",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Brown 9`,
          },
          {
            id: "ds44625fefdds",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Brown 10`,
          },
        ],
      },
      {
        content: "This is a random quote DARK BLUE",
        by: "User Name",
        background:
          "linear-gradient(120deg, rgba(3,8,116,1) 0%, rgba(203,2,2,1) 100%)",
        tags: ["#DBL", "#BR"],
        approves: [],
        disapproves: [],
        comments: [
          {
            id: "dsdsweg",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Dark Blue 1`,
          },
          {
            id: "dsd45s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Dark Blue 2`,
          },
          {
            id: "dsds79879",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Dark Blue 3`,
          },
          {
            id: "dsd3479976s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Dark Blue 4`,
          },
          {
            id: "dsds12421",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Dark Blue 5`,
          },
          {
            id: "dsd42353256s",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Dark Blue 6`,
          },
          {
            id: "dsds6765754",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Dark Blue 7`,
          },
          {
            id: "dsd23905hfs",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Dark Blue 8`,
          },
          {
            id: "dsds425gds",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Dark Blue 9`,
          },
          {
            id: "ds44625fefdds",
            userId: "gdsgdsgds",
            userAvatar: "/images/temporary/Avatar4.png",
            userSignature: "#ASKTH",
            content: `Dark Blue 10`,
          },
        ],
      },
      {
        content: "This is a random quote LIGHT BLUE",
        by: "User Name",
        background:
          "linear-gradient(120deg, rgba(0,232,238,1) 0%, rgba(235,2,2,1) 100%)",
        tags: ["#LBL", "#BR"],
        approves: [
          "dsds",
          "dsgds",
          "sgds",
          "gsgsgr",
          "dsds",
          "dsgds",
          "sgds",
          "gsgsgr",
        ],
        disapproves: ["dsds", "dsgds", "sgds", "gsgsgr"],
        comments: [],
      },
    ],
  },
];
